"""Story 1.11: a named detail is bound to a frozen ``QuerySpec``, once, before the data.

The story's acceptance criteria are five claims, and each has a section below:

1. **AD-1** -- exactly one frozen spec per answerable question, produced before any data
   access, and no layer past ``compile/`` can set, widen or reinterpret a field.
2. **AD-19** -- one ladder per field (named-in-question, inherited-from-history, rule
   default, ``Unbound``), walked before the spec is constructed, with exactly one binder
   owning each field.
3. **FR-4, FR-5, FR-6** -- a named grain beats every other signal including the newest
   row's; an unnamed grain takes the detail's *declared* default; a grain the detail does
   not publish is stated rather than swapped for a neighbour.
4. **FR-10, FR-11b** -- no country named means national scope, which is a query shape and
   never a country filter value.
5. **FR-14 and NFR-1/AD-17** -- every field records whose authority it carries, no field
   is bound by a model in this epic, and the same inputs compile to an identical spec.

Several of these are asserted structurally -- by a scan, or by a type that cannot
represent the violation -- rather than by example, because the defects they exist to
prevent are all defects of *reach*: some later layer that could touch a field, or a
binder that could see a row. An example shows it did not happen this time.
"""

from __future__ import annotations

import ast
import dataclasses
from datetime import date
from pathlib import Path

import pytest

from askai.compile.binder import CompileInput, compile_question
from askai.compile.binding import (
    Binding,
    BoundBy,
    CompiledQuestion,
    Precedence,
    SpecField,
    UnboundReason,
    bindable_fields,
    unbound,
)
from askai.compile.catalogue import CatalogueCountry, CatalogueDetail, snapshot
from askai.compile.lexicon import (
    BindingRule,
    default_country_scope,
    default_measure,
    default_operation,
    grain_words,
    latest_words,
    measure_words,
    month_numbers,
    quarter_numbers,
    readings_for_latest,
)
from askai.compile.question import Question
from askai.domain.normalise import normalise
from askai.domain.period import Grain, Period
from askai.domain.scope import DeclaredBenchmarks, Named, National
from askai.domain.spec import (
    Bound,
    Deferred,
    Exact,
    LastN,
    Latest,
    Measure,
    Operation,
    QuerySpec,
    Unbound,
)
from askai.ports.catalogue import CataloguePort
from askai.rules import rules
from corpus_runner import EMPTY_CATALOGUE, load_corpus

PROJECT_ROOT = Path(__file__).resolve().parent.parent
PACKAGE_ROOT = PROJECT_ROOT / "src" / "askai"

TODAY = date(2026, 9, 15)

# One indicator publishing at all three grains, one publishing at two, one publishing at
# none, and one name two details share. Every shape the binders have to tell apart, and
# no more: a fixture the size of the catalogue would hide which one a failure is about.
CATALOGUE = snapshot(
    details=[
        CatalogueDetail(
            detail_id="D-INFLATION",
            names=("Inflation", "معدل التضخم"),
            declared_grain=Grain.MONTHLY,
            grains=frozenset(Grain),
        ),
        CatalogueDetail(
            detail_id="D-REAL-GDP",
            names=("Real GDP", "الناتج المحلي الإجمالي الحقيقي"),
            declared_grain=Grain.YEARLY,
            grains=frozenset({Grain.QUARTERLY, Grain.YEARLY}),
        ),
        CatalogueDetail(
            detail_id="D-SOLAR",
            names=("Percentage of energy generated by solar",),
        ),
        CatalogueDetail(detail_id="D-SHARED-ONE", names=("Employment Rate",)),
        CatalogueDetail(detail_id="D-SHARED-TWO", names=("Employment Rate",)),
    ],
    countries=[
        CatalogueCountry(country_id="C-JAPAN", names=("Japan", "اليابان")),
        CatalogueCountry(country_id="C-OMAN", names=("Oman", "عمان")),
    ],
)


def compiled(question: str, *, history: tuple[str, ...] = ()) -> CompiledQuestion:
    return compile_question(
        CompileInput(question=question, today=TODAY, history=history), CATALOGUE
    )


def period_of(question: str, *, history: tuple[str, ...] = ()) -> object:
    return compiled(question, history=history).spec.period


def _modules(root: Path) -> list[tuple[Path, ast.Module]]:
    return [
        (path, ast.parse(path.read_text(encoding="utf-8"), filename=str(path)))
        for path in sorted(root.rglob("*.py"))
    ]


# ------------------------------------------------- AD-1: one spec, frozen, before data


def test_exactly_one_query_spec_is_constructed_in_the_whole_tree() -> None:
    """"Produced exactly once per answerable question" needs one producer, not a habit.

    A second construction site is how a field comes to be set twice -- the AD-1 defect
    arriving as a helper rather than as a decision. The scan finds the call, not the
    import, so re-exporting the type stays free.
    """
    sites = [
        f"{path.relative_to(PACKAGE_ROOT).as_posix()}:{node.lineno}"
        for path, tree in _modules(PACKAGE_ROOT)
        for node in ast.walk(tree)
        if isinstance(node, ast.Call)
        and isinstance(node.func, ast.Name)
        and node.func.id == QuerySpec.__name__
    ]
    assert len(sites) == 1, "a QuerySpec is constructed in more than one place: " + ", ".join(
        sites
    )
    assert sites[0].startswith("compile/binder.py:"), f"a QuerySpec is built in {sites[0]}"


def test_no_layer_past_compile_can_set_a_field() -> None:
    """The frozen type, asserted rather than assumed.

    There is no setter to forbid, so the assertion is that assignment itself fails --
    on every bindable field, so that a field added later without ``frozen`` is caught.
    """
    spec = compiled("What was inflation in April 2026?").spec
    for field in bindable_fields():
        with pytest.raises(dataclasses.FrozenInstanceError):
            setattr(spec, field, Unbound(reason="rewritten downstream"))


def test_compiling_reads_no_clock() -> None:
    """AD-17: ``today`` is an input. A clock read in pure code is the determinism gate
    failing quietly on a date boundary rather than in a test."""
    offenders = [
        f"{path.relative_to(PACKAGE_ROOT).as_posix()}:{node.lineno}"
        for path, tree in _modules(PACKAGE_ROOT / "compile")
        for node in ast.walk(tree)
        if isinstance(node, ast.Attribute)
        and node.attr in {"today", "now", "utcnow", "time", "monotonic"}
        and isinstance(node.value, ast.Name)
        and node.value.id in {"date", "datetime", "time", "clock"}
    ]
    assert not offenders, "compile/ reads a clock: " + ", ".join(offenders)


def test_the_catalogue_port_cannot_return_a_figure_a_period_or_a_row() -> None:
    """"Before any data access", made structural.

    The binder holds one port, and these are all of its methods. None of them can return
    a value, a row, or a period that exists in the data, so a binder cannot consult the
    newest row even by accident -- which is the signal FR-4 and FR-5 exist to overrule.
    """
    surface = {name for name in vars(CataloguePort) if not name.startswith("_")}
    assert surface == {
        "details_named",
        "default_grain",
        "published_grains",
        "country_named",
        # A count of words over the published *names*, which binding already reads. It
        # returns an int and can express no figure, period or row, so it widens the
        # surface without weakening the claim above -- admitted deliberately, because a
        # method that could return data must never be added here by reflex.
        "longest_name_words",
    }


def test_compile_imports_no_adapter_and_no_later_layer() -> None:
    """AD-2 at the module level, so a failure names the import rather than the contract."""
    forbidden = ("askai.adapters", "askai.execute", "askai.assemble", "askai.narrate")
    offenders = [
        f"{path.relative_to(PACKAGE_ROOT).as_posix()}:{node.lineno} {name}"
        for path, tree in _modules(PACKAGE_ROOT / "compile")
        for node in ast.walk(tree)
        if isinstance(node, ast.ImportFrom)
        for name in [node.module or ""]
        if name.startswith(forbidden)
    ]
    assert not offenders, "compile/ reaches past its layer: " + ", ".join(offenders)


# --------------------------------------------------------- AD-19: one ladder, one binder


def test_the_precedence_in_code_is_the_precedence_in_the_rules() -> None:
    """AD-19's ladder is stated as data; the binders walk it in that order."""
    assert tuple(step.value for step in Precedence) == rules().value(
        BindingRule.PRECEDENCE.value, "order"
    )


def test_every_spec_field_has_a_binder_and_no_field_has_two() -> None:
    """The set of owned fields is read off ``QuerySpec`` itself, so a field added to the
    spec without a binder fails here instead of defaulting to whatever a binder forgot."""
    assert tuple(field.value for field in SpecField) == bindable_fields()


def test_a_missing_binder_is_refused() -> None:
    account = compiled("What was inflation in April 2026?")
    with pytest.raises(ValueError, match="exactly one binder"):
        CompiledQuestion(spec=account.spec, bindings=account.bindings[1:])


def test_two_binders_for_one_field_are_refused() -> None:
    account = compiled("What was inflation in April 2026?")
    twice = (*account.bindings, account.bindings[0])
    with pytest.raises(ValueError, match="exactly one binder"):
        CompiledQuestion(spec=account.spec, bindings=twice)


def test_a_binding_that_disagrees_with_the_spec_is_refused() -> None:
    """The account and the spec are one statement. A record claiming a field was bound
    while the spec carries ``Unbound`` would make the record decorative."""
    account = compiled("What is the price of tea?")
    lying = tuple(
        Binding(field=binding.field, precedence=Precedence.RULE_DEFAULT, bound_by=BoundBy.RULE)
        if binding.field is SpecField.DETAIL
        else binding
        for binding in account.bindings
    )
    with pytest.raises(ValueError, match="one statement"):
        CompiledQuestion(spec=account.spec, bindings=lying)


def test_a_bound_field_with_no_binder_is_refused() -> None:
    with pytest.raises(ValueError, match="bound by someone"):
        Binding(field=SpecField.MEASURE, precedence=Precedence.RULE_DEFAULT, bound_by=None)


def test_named_in_question_outranks_history_and_the_rule_default() -> None:
    account = compiled(
        "What was Real GDP in 2025?", history=("What was inflation in April 2026?",)
    )
    assert account.spec.detail == Bound("D-REAL-GDP")
    assert account.by_field[SpecField.DETAIL].precedence is Precedence.NAMED_IN_QUESTION
    assert account.by_field[SpecField.DETAIL].bound_by is BoundBy.READER


def test_history_outranks_the_rule_default_and_only_where_the_question_is_silent() -> None:
    """A follow-up overrides only the fields its own question names (AD-19)."""
    account = compiled("What about 2022?", history=("What was Real GDP in 2025?",))
    assert account.spec.detail == Bound("D-REAL-GDP")
    assert account.spec.period == Bound(Exact(Period("2022")))
    assert account.by_field[SpecField.DETAIL].precedence is Precedence.INHERITED_FROM_HISTORY
    assert account.by_field[SpecField.PERIOD].precedence is Precedence.NAMED_IN_QUESTION


def test_an_earlier_unbound_field_is_not_inherited() -> None:
    """Carrying "the reader was not specific enough" forward would answer this question
    with the previous one's ambiguity."""
    account = compiled("What about 2022?", history=("What is the price of tea?",))
    assert isinstance(account.spec.detail, Unbound)
    assert account.by_field[SpecField.DETAIL].precedence is Precedence.UNBOUND


def test_the_rule_default_applies_when_nothing_named_and_nothing_inherited() -> None:
    account = compiled("What was inflation in April 2026?")
    assert account.spec.measure == Bound(default_measure())
    assert account.spec.operation == Bound(default_operation())
    assert account.spec.country_scope == Bound(default_country_scope())
    for field in (SpecField.MEASURE, SpecField.OPERATION, SpecField.COUNTRY_SCOPE):
        assert account.by_field[field].precedence is Precedence.RULE_DEFAULT
        assert account.by_field[field].bound_by is BoundBy.RULE


def test_unbound_is_the_last_rung_and_carries_a_stated_cause() -> None:
    account = compiled("What is the price of tea?")
    detail = account.spec.detail
    assert isinstance(detail, Unbound)
    assert detail.reason.startswith(UnboundReason.NO_DETAIL_NAMED.value)
    assert account.by_field[SpecField.DETAIL].bound_by is None
    assert not account.is_answerable


def test_a_name_two_details_share_is_refused_rather_than_chosen_between() -> None:
    """257 of 320 published names are ambiguous; picking one is Epic 2's job and is
    structural before it is semantic (AD-25). Epic 1 states the ambiguity."""
    detail = compiled("What is the employment rate?").spec.detail
    assert isinstance(detail, Unbound)
    assert detail.reason.startswith(UnboundReason.DETAIL_NAME_IS_SHARED.value)
    assert "D-SHARED-ONE" in detail.reason and "D-SHARED-TWO" in detail.reason


# ---------------------------------------------------- exact normalised-name lookup only


@pytest.mark.parametrize(
    "asked",
    [
        "What was inflation in April 2026?",
        "WHAT WAS INFLATION IN APRIL 2026?",
        "What was  Inflation, in April 2026?",
        "كم بلغ معدل التضخم في أبريل 2026؟",
        "كم بلغ معدل التضخم في ابريل 2026؟",
    ],
)
def test_a_name_resolves_through_the_one_normalisation(asked: str) -> None:
    """Case, punctuation, spacing and Arabic hamza spelling are the *same* name, because
    the catalogue and the question are folded by the same function (AD-26)."""
    assert compiled(asked).spec.detail == Bound("D-INFLATION")


@pytest.mark.parametrize("asked", ["What was inflatoin?", "gdp", "How is the economy?"])
def test_a_name_that_is_not_the_published_name_resolves_to_nothing(asked: str) -> None:
    """Epic 1 is exact lookup. There is no nearest match, because there is no score.

    ``gdp`` is the sharp one: the catalogue publishes *Real GDP*, and an engine that
    resolved the shorter string to it would be scoring, which is Epic 2's ladder arriving
    early and unstated.
    """
    assert isinstance(compiled(asked).spec.detail, Unbound)


def test_the_longer_published_name_wins_over_the_shorter_one_inside_it() -> None:
    catalogue = snapshot(
        details=[
            CatalogueDetail(detail_id="D-GDP", names=("GDP",)),
            CatalogueDetail(detail_id="D-GDP-DEFLATOR", names=("GDP Deflator",)),
        ]
    )
    account = compile_question(
        CompileInput(question="What is the GDP deflator?", today=TODAY), catalogue
    )
    assert account.spec.detail == Bound("D-GDP-DEFLATOR")


# ------------------------------------------------------- FR-4, FR-5, FR-6: grain


def test_a_grain_named_in_the_question_wins_over_the_declared_default() -> None:
    """FR-4. Inflation declares monthly; the question says yearly, so it is yearly."""
    assert period_of("What was yearly inflation?") == Deferred(
        LastN(n=readings_for_latest(), grain=Grain.YEARLY)
    )


def test_a_grain_named_in_the_question_wins_over_the_period_it_inherited() -> None:
    """FR-4 through a follow-up: "and monthly?" moves the grain and nothing else."""
    account = compiled("And monthly?", history=("What was inflation in 2026-Q1?",))
    assert account.spec.detail == Bound("D-INFLATION")
    assert account.spec.period == Deferred(LastN(n=readings_for_latest(), grain=Grain.MONTHLY))
    assert account.by_field[SpecField.PERIOD].precedence is Precedence.NAMED_IN_QUESTION
    assert account.by_field[SpecField.DETAIL].precedence is Precedence.INHERITED_FROM_HISTORY


def test_the_arabic_follow_up_moves_the_grain_the_same_way() -> None:
    account = compiled("وشهرياً؟", history=("كم بلغ معدل التضخم في الربع الأول من 2026؟",))
    assert account.spec.period == Deferred(LastN(n=readings_for_latest(), grain=Grain.MONTHLY))


def test_a_period_phrase_implying_a_grain_counts_as_naming_one() -> None:
    """FR-5's second half: "April 2026" names monthly as surely as the word "monthly"."""
    assert period_of("What was inflation in April 2026?") == Bound(Exact(Period("2026-04")))
    assert period_of("What was inflation in the first quarter of 2026?") == Bound(
        Exact(Period("2026-Q1"))
    )
    assert period_of("What was Real GDP in 2025?") == Bound(Exact(Period("2025")))


def test_with_no_grain_named_the_detail_s_declared_default_is_used() -> None:
    """FR-5. Real GDP declares yearly even though it also publishes quarterly."""
    assert period_of("What is Real GDP now?") == Deferred(
        LastN(n=readings_for_latest(), grain=Grain.YEARLY)
    )
    assert period_of("What is inflation now?") == Deferred(
        LastN(n=readings_for_latest(), grain=Grain.MONTHLY)
    )


def test_the_declared_default_is_asked_of_the_catalogue_not_of_the_data() -> None:
    """FR-5's whole content: *not* the grain of the latest row.

    The catalogue here declares yearly for a detail that publishes quarterly as well, so
    a binder reading the newest row would have to answer quarterly to be wrong -- and it
    has no way to read one, which is the port's doing.
    """
    declared = CATALOGUE.default_grain("D-REAL-GDP")
    assert declared is Grain.YEARLY
    assert Grain.QUARTERLY in CATALOGUE.published_grains("D-REAL-GDP")


def test_a_detail_declaring_no_default_leaves_latest_ungrained() -> None:
    """``Latest`` carries no grain, and inventing one would be compile choosing a grain
    the catalogue never declared."""
    assert period_of("What is the percentage of energy generated by solar now?") == Deferred(
        Latest()
    )


def test_a_grain_the_detail_does_not_publish_is_stated_and_never_substituted() -> None:
    """FR-6. Real GDP publishes quarterly and yearly; monthly is refused as monthly."""
    state = period_of("What was monthly Real GDP?")
    assert isinstance(state, Unbound)
    assert state.reason.startswith(UnboundReason.GRAIN_NOT_PUBLISHED.value)
    assert Grain.MONTHLY.value in state.reason
    assert Grain.QUARTERLY.value in state.reason and Grain.YEARLY.value in state.reason


def test_a_named_period_at_an_unpublished_grain_is_refused_too() -> None:
    """The grain arrives inside the period, and it is refused the same way -- a quarter
    is never answered with the year that contains it."""
    state = period_of("What was Real GDP in April 2025?")
    assert isinstance(state, Unbound)
    assert state.reason.startswith(UnboundReason.GRAIN_NOT_PUBLISHED.value)


def test_a_grain_is_never_checked_against_a_detail_that_is_not_bound() -> None:
    """With no detail there is nothing to publish a grain, so the period still binds."""
    account = compiled("What was the monthly price of tea?")
    assert isinstance(account.spec.detail, Unbound)
    assert account.spec.period == Deferred(LastN(n=readings_for_latest(), grain=Grain.MONTHLY))


def test_more_than_one_named_period_is_unbound_rather_than_guessed() -> None:
    """A span is Epic 3's; two periods named here are an ambiguity, not a range to infer."""
    state = period_of("What was inflation between 2019 and 2025?")
    assert isinstance(state, Unbound)
    assert state.reason.startswith(UnboundReason.MORE_THAN_ONE_PERIOD_NAMED.value)


def test_a_month_with_no_year_names_no_period() -> None:
    """Picking the year would be compile inventing a period the reader never named."""
    assert period_of("What was inflation in April?") == Deferred(
        LastN(n=readings_for_latest(), grain=Grain.MONTHLY)
    )


# ----------------------------------------------------- FR-10, FR-11b: national scope


def test_no_country_named_binds_the_national_query_shape() -> None:
    account = compiled("What was inflation in April 2026?")
    assert account.spec.country_scope == Bound(National())
    assert account.by_field[SpecField.COUNTRY_SCOPE].precedence is Precedence.RULE_DEFAULT


def test_naming_the_home_country_is_naming_no_country() -> None:
    """AD-5 as an absence rather than a special case: the home country is published in no
    row and so is in no catalogue of countries, so naming it matches nothing and the
    scope falls to national."""
    for asked in ("What was inflation in Qatar in April 2026?", "كم بلغ التضخم في قطر؟"):
        scope = compile_question(
            CompileInput(question=asked, today=TODAY), CATALOGUE
        ).spec.country_scope
        assert scope == Bound(National())


def test_a_named_country_binds_a_named_set_of_ids_not_of_names() -> None:
    scope = compiled("How does Real GDP compare with Japan and Oman?").spec.country_scope
    assert scope == Bound(Named(countries=frozenset({"C-JAPAN", "C-OMAN"})))


def test_asking_for_benchmarks_binds_the_declared_set() -> None:
    scope = compiled("How does Real GDP compare with our benchmarks?").spec.country_scope
    assert scope == Bound(DeclaredBenchmarks())


def test_no_call_site_constructs_a_country_filter_containing_the_home_country() -> None:
    """The AC's own words, asserted over the whole package rather than over ``domain/``.

    The literal is spelled by folding it from its own letters, so this test can assert
    the absence without being the one file that contains it.

    One exemption, the same one ``tests/test_domain_invariants.py`` argues for: the root
    package docstring says what the product is for, in prose, and holds no code. Naming
    the country in a sentence is not the defect; constructing a filter from it is.
    """
    home = normalise("".join(chr(point) for point in (0x51, 0x61, 0x74, 0x61, 0x72)))
    offenders = [
        f"{path.relative_to(PACKAGE_ROOT).as_posix()}:{node.lineno}"
        for path, tree in _modules(PACKAGE_ROOT)
        if path.relative_to(PACKAGE_ROOT).as_posix() != "__init__.py"
        for node in ast.walk(tree)
        if isinstance(node, ast.Constant)
        and isinstance(node.value, str)
        and home in normalise(node.value)
    ]
    assert not offenders, "the home country is named as a literal: " + ", ".join(offenders)


# ------------------------------------------------ FR-14: how each field was bound


def test_every_field_records_whose_authority_it_carries() -> None:
    account = compiled("What was the target for inflation in 2026?")
    for binding in account.bindings:
        if binding.precedence is Precedence.UNBOUND:
            assert binding.bound_by is None
        else:
            assert binding.bound_by in set(BoundBy)


def test_no_field_is_ever_bound_by_a_model_in_this_epic() -> None:
    """The epic makes no model call, so the value is unreachable rather than unused."""
    for asked in (
        "What was inflation in April 2026?",
        "What is Real GDP now?",
        "What is the price of tea?",
        "And monthly?",
    ):
        account = compiled(asked, history=("What was inflation in 2026-Q1?",))
        assert all(binding.bound_by is not BoundBy.MODEL for binding in account.bindings)
        assert all(binding.bound_by is not BoundBy.SEMANTIC for binding in account.bindings)


def test_a_measure_named_in_the_question_is_bound_by_the_reader() -> None:
    account = compiled("What was the target for inflation in 2026?")
    assert account.spec.measure == Bound(Measure.TARGET)
    assert account.by_field[SpecField.MEASURE].precedence is Precedence.NAMED_IN_QUESTION


def test_a_measure_word_inside_the_detail_s_own_name_does_not_count() -> None:
    """An indicator called *Growth* is not a question about change."""
    catalogue = snapshot(
        details=[CatalogueDetail(detail_id="D-GDP-GROWTH", names=("Real GDP Growth",))]
    )
    account = compile_question(
        CompileInput(question="What was Real GDP Growth in 2025?", today=TODAY), catalogue
    )
    assert account.spec.detail == Bound("D-GDP-GROWTH")
    assert account.spec.measure == Bound(default_measure())


def test_the_operation_is_the_rule_default_because_nothing_classifies_one_here() -> None:
    """Operation classification is a bounded model call-site (AD-22) and arrives later.
    Binding it by rule now means the classifier replaces a named default, not a habit."""
    account = compiled("What was inflation in April 2026?")
    assert account.spec.operation == Bound(Operation.VALUE)
    assert account.by_field[SpecField.OPERATION].bound_by is BoundBy.RULE


# ------------------------------------------------------- NFR-1, AD-17: determinism


@pytest.mark.parametrize(
    "asked",
    [
        "What was inflation in April 2026?",
        "What is Real GDP now?",
        "How does Real GDP compare with Japan and Oman?",
        "What is the employment rate?",
        "كم بلغ معدل التضخم في أبريل 2026؟",
    ],
)
def test_the_same_question_compiles_to_an_identical_spec_every_time(asked: str) -> None:
    accounts = [compiled(asked) for _ in range(5)]
    assert all(account == accounts[0] for account in accounts)
    assert all(account.spec == accounts[0].spec for account in accounts)


def test_today_is_an_input_and_reaches_the_spec_unchanged() -> None:
    for pinned in (date(2019, 1, 1), TODAY, date(2030, 12, 31)):
        account = compile_question(
            CompileInput(question="What is inflation now?", today=pinned), CATALOGUE
        )
        assert account.spec.today == pinned


def test_two_questions_differing_only_by_today_differ_only_by_today() -> None:
    first = compile_question(
        CompileInput(question="What is inflation now?", today=TODAY), CATALOGUE
    )
    later = compile_question(
        CompileInput(question="What is inflation now?", today=date(2027, 1, 1)), CATALOGUE
    )
    assert first.spec != later.spec
    assert dataclasses.replace(first.spec, today=later.spec.today) == later.spec


# ------------------------------------------------- the constants are rules, not code


def test_every_default_comes_out_of_the_rule_files() -> None:
    """Not "a default exists" but "this default is that clause"."""
    assert default_measure().value == rules().value(BindingRule.DEFAULT_MEASURE.value, "measure")
    assert default_operation().value == rules().value(
        BindingRule.DEFAULT_OPERATION.value, "operation"
    )
    assert readings_for_latest() == rules().value(
        BindingRule.GRAIN_FROM_DECLARED_DEFAULT.value, "readings"
    )
    assert rules().value(BindingRule.DEFAULT_COUNTRY_SCOPE.value, "scope") == "national"


def test_every_binding_rule_is_loaded_and_fireable() -> None:
    for rule in BindingRule:
        assert rules().fire(rule.value).is_fireable


@pytest.mark.parametrize(
    "words",
    [
        *grain_words().values(),
        *measure_words().values(),
        latest_words(),
        frozenset(month_numbers()),
        frozenset(quarter_numbers()),
    ],
    ids=lambda words: f"{len(words)}-phrases",
)
def test_every_phrase_in_the_rule_files_is_already_in_normal_form(words: frozenset[str]) -> None:
    """A phrase that is not in normal form can never match, because the question always
    is. Silent, permanent, and exactly finding 121's Arabic half."""
    assert {phrase for phrase in words if normalise(phrase) != phrase} == set()


def test_a_grain_added_to_the_domain_would_need_words_rather_than_silently_have_none() -> None:
    assert set(grain_words()) == set(Grain)
    assert set(measure_words()) == set(Measure)


# ----------------------------------------------------------------- the question surface


def test_a_span_is_a_run_of_words_and_never_crosses_the_middle_of_one() -> None:
    question = Question.parse("real gdp deflator")
    assert {span.text for span in question.spans()} == {
        "real",
        "gdp",
        "deflator",
        "real gdp",
        "gdp deflator",
        "real gdp deflator",
    }


def test_the_raw_words_keep_the_period_spelling_the_fold_would_collapse() -> None:
    """``2026-04`` folded is ``2026 04``, which is not a published period."""
    question = Question.parse("What was inflation in 2026-04?")
    assert "2026-04" in question.raw_words
    assert "2026-04" not in question.words


def test_an_unbound_reason_is_a_code_and_not_a_sentence() -> None:
    """Reader-facing text is composed in ``narrate/`` from the bilingual catalogue; the
    cause is carried as a closed code so either language can say it."""
    assert unbound(UnboundReason.NO_DETAIL_NAMED, "tea").reason.startswith("no-detail-named")


# ------------------------------------------------------------------------- the corpus


def test_every_corpus_entry_compiles_to_a_query_spec() -> None:
    """The seam is live: if ``run_entry`` stopped compiling anything, this goes red.

    Compiled against the empty catalogue the runner uses, so it asserts what the binder
    owns -- totality, one binder per field, determinism -- on every committed entry, with
    no database anywhere.
    """
    entries = load_corpus()
    assert entries, "the corpus is empty; there is nothing to compile"
    for entry in entries:
        asked = entry.data["question"]
        for language, text in sorted(asked.items()):
            account = compile_question(
                CompileInput(question=text, today=entry.data["today"]), EMPTY_CATALOGUE
            )
            assert account.spec.today == entry.data["today"], f"{entry.source} {language}"
            assert len(account.bindings) == len(bindable_fields())


def test_compiling_is_total_even_when_nothing_resolves() -> None:
    """A question the engine cannot resolve produces a spec whose fields are ``Unbound``
    -- never an exception, because a refusal has to be an answer with a reason on it."""
    account = compile_question(
        CompileInput(question="?????", today=TODAY), EMPTY_CATALOGUE
    )
    assert isinstance(account.spec.detail, Unbound)
    assert not account.is_answerable
