"""The corpus, answered -- the gate that says whether a question gets the right outcome.

``tests/corpus_runner.py`` compiles every entry against a **deliberately empty catalogue**
and asserts the binder's own properties: compiling is total, every field is bound once
with its precedence recorded, and the same question compiles identically on every run. It
never reads ``expected:``, never executes, and never checks whether a question is
answered.

So until this file existed, **nothing in this repository measured whether the engine
answers anything**. That is not a hypothetical gap. On 2026-09-17 a build that answered 9
of 95 corpus questions passed all five gates for days, and three separate defects reached
the target VM: an execution layer that produced one shape, a resolution ladder that was
never wired, and a catalogue that offered the home country as a filterable name. Every one
of them was found by running questions by hand.

**What this asserts.** Each corpus entry's question, through the real answer path, against
a real ingested estate, and the resulting package ``kind`` compared with the entry's
``expected``. Nothing more: this is the coarsest useful assertion, and it is worth having
because the three defects above all changed a ``kind``.

**What this does not assert, and must not be read as.** A ``kind`` of ``answer`` can still
be the *wrong* answer. ``e1-005`` ("What percentage of Qatar's energy is generated by
solar?") answers with *"Energy was 130.90 Index Points"* -- an unrelated indicator matched
on the bare word ``energy``. ``e5-012`` asks which periods are available and gets a
figure. Both would satisfy a ``kind`` comparison. Asserting on the composed text is the
next increment of this gate, not a replacement for it.

**Some entries pass for the wrong reason, and the gate cannot tell.** ``e6-002`` ("Why
did inflation move in April 2026?") expects an answer and gets one -- the bare figure,
not the analyst note it is asking for, so it will keep passing when Session U makes it
answer properly. ``e7-004`` and ``e6-005`` expect refusals and get them because the
feature does not exist at all. A passing row here means the outcome matched, never that
the answer was right.

**The ladder is deliberately off here.** ``engine_for`` is called without a
``CandidatePort``, so only exact published-name matching runs. That keeps this gate
deterministic and runnable with no embedding endpoint (NFR-6). It also means the numbers
here are the floor: a deployment with an index generation answers more, and differently.
Retrieval quality is measured by the AD-30 harness, not by this file.

**``KNOWN_GAPS`` is the point of the design.** A gate that is red everywhere is ignored, so
the entries that do not yet reach their expected outcome are listed with the reason and
the session that owns each. The list is asserted to be *exact*: an entry that starts
passing fails this suite until it is removed. That is deliberate -- it makes the list
shrink, and it makes a fix impossible to land silently.
"""

from __future__ import annotations

import glob
from collections.abc import Iterator
from datetime import UTC, date, datetime
from pathlib import Path
from typing import Final

import pytest
import yaml

from askai.adapters.readmodel.export import CmsExport
from askai.adapters.readmodel.ingest import ingest_published_layer
from askai.adapters.readmodel.startup import engine_for
from askai.adapters.store.provision import Databases, provision
from askai.api.ask import Ask, answer_question
from askai.domain.admission import SourceAdmission
from askai.messages import Lang

PROJECT_ROOT: Final = Path(__file__).resolve().parent.parent
EXPORT_ROOT: Final = PROJECT_ROOT / "data"

#: The date an entry is answered at when it declares none. A fixed date, never
#: ``date.today()``: ``today`` is an input to compiling (AD-17) and a clock read here
#: would make every deferred-period entry bind differently tomorrow.
DEFAULT_TODAY: Final = "2026-09-17"

#: Entries whose expected outcome the engine does not yet produce, each with the session
#: that owns it. Asserted to be exact by ``test_the_known_gaps_are_exactly_the_failures``:
#: remove an entry the moment it starts passing.
KNOWN_GAPS: Final[dict[str, str]] = {
    # Session R -- needs AD-25's ladder, which needs an index generation and a real
    # embedding endpoint. Refused here as `no-such-indicator` by design, not by defect.
    "e1-004": "R: paraphrase, no exact published name",
    "e2-003": "R: paraphrase, no exact published name",
    "e2-010": "R: paraphrase, no exact published name",
    "e2-011": "R: paraphrase, no exact published name",
    "e2-012": "R: paraphrase, no exact published name",
    "e2-015": "R: paraphrase, no exact published name",
    "e2-025": "R: paraphrase; expects a clarification naming candidates",
    "e2-026": "T: a follow-up; needs conversation history",
    "e4-004": "R: paraphrase, no exact published name",
    "e4-011": "R: paraphrase, no exact published name",
    "e5-007": "R: paraphrase, no exact published name",
    "e5-008": "L: capability question; no composer reached",
    "e5-013": "R: paraphrase, no exact published name",
    "e5-016": "L: share-of-total; execute/ has no shape for it",
    "e5-018": "R: paraphrase, no exact published name",
    "e5-019": "R: paraphrase, no exact published name",
    # Session L, in flight -- the series switch (R-OP-SERIES-FROM-A-MULTI-READING-REQUEST)
    # is on while relative windows still refuse, so these regressed from a partial answer
    # to a refusal. The rule's own note calls that the worse outcome. See
    # _bmad-output/implementation-artifacts/review-findings-session-l.md.
    "e2-009": "L: relative window ('over the last 5 years') binds series, then refuses",
    "e5-017": "L: relative window ('over the last five years') binds series, then refuses",
    # Session Q, verified against its committed state (4a995e7). Both refuse where the
    # corpus expects a figure -- "What is Qatar's obesity rate?" and "How much of the
    # economy does not come from oil and gas?" name no published indicator exactly, so
    # they are really waiting on the ladder rather than on Q.
    "e2-007": "R: paraphrase; refuses where a figure is expected",
    "e2-014": "R: paraphrase; refuses where a figure is expected",
    # Session L -- execute/ has no shape for the operation, or the composer is unreached.
    "e2-024": "L: explanation operation",
    "e3-004": "L: change operation",
    "e3-005": "L: change operation",
    "e3-006": "L: period comparison",
    "e3-008": "L: baseline lookup",
    "e3-013": "L: series plus comparison in one question",
    "e4-001": "L: cross-country comparison",
    "e4-002": "L: cross-country comparison",
    "e4-003": "L: extremum across countries",
    "e4-005": "L: spread across countries",
    "e4-008": "L: a named country's own value",
    "e4-009": "L: cross-country comparison",
    "e4-010": "L: cross-indicator comparison",
    "e5-001": "L: count over a group",
    "e5-002": "L: list over a group",
    "e5-003": "L: extremum over groups",
    "e5-004": "L: list over a group",
    "e5-010": "L: list over a group",
    "e5-011": "L: count over a group",
    "e5-014": "L: definition of a shared name; expects a clarification",
    # Session Q -- answers that must refuse. The severity is in the brief.
    "e1-005": "Q: binds `Energy` on a bare word; answers about solar with an index",
    "e6-003": "Q: 'why' answered with the figure",
    "e9-002": "Q: binds `Oil` on a bare word",
    # Session U -- the analyst commentary is loaded and unreachable.
    "e6-001": "U: needs the commentary port on Engine",
    # Session O -- articles are not indexed.
    "e6-004": "O: articles not indexed",
    # Session S -- the external contract.
    "e2-002": "S/R: expects a refusal, gets a clarification",
    # Session T -- follow-ups need conversation history.
    "e7-001": "T: follow-up",
    "e7-002": "T: follow-up",
    "e7-003": "T: multi-part; needs the MULTI_PART_DETECTION prompt, which does not exist",
    # Session G -- prose.
    "e8-001": "G: prose over an assembled answer",
    "e8-002": "G: prose over an assembled answer",
}


@pytest.fixture(scope="module")
def databases() -> Iterator[Databases]:
    with provision() as estate:
        ingest_published_layer(estate.read_model, CmsExport.rooted(EXPORT_ROOT))
        yield estate


@pytest.fixture(scope="module")
def state_file(tmp_path_factory: pytest.TempPathFactory) -> Path:
    return tmp_path_factory.mktemp("estate") / "refresh_state.json"


def _entries() -> list[tuple[str, str, str, str]]:
    """``(id, question, expected, today)`` for every corpus entry with English text.

    English only, deliberately: this gate is about whether the engine reaches an outcome,
    and ``tests/test_bilingual_parity.py`` already owns the claim that both languages say
    the same thing. One entry (``e10-002``) carries no English text at all, which is an
    authoring slip recorded in ``sessions/session-n-deploy-and-verify.md``.
    """
    found: list[tuple[str, str, str, str]] = []
    for path in sorted(glob.glob(str(PROJECT_ROOT / "corpus" / "*.yaml"))):
        for entry in yaml.safe_load(Path(path).read_text(encoding="utf-8")) or []:
            if not isinstance(entry, dict) or "question" not in entry:
                continue
            asked = entry["question"]
            english = asked.get("en") if isinstance(asked, dict) else asked
            if not english:
                continue
            when = entry.get("today") or DEFAULT_TODAY
            found.append(
                (
                    str(entry.get("id", "")),
                    str(english).strip(),
                    str(entry.get("expected", "answer")),
                    when.isoformat() if isinstance(when, date) else str(when),
                )
            )
    return found


CORPUS: Final = _entries()


def _outcome(databases: Databases, state_file: Path, question: str, when: str) -> str:
    moment = datetime.fromisoformat(f"{when}T12:00:00+00:00").astimezone(UTC)
    engine = engine_for(databases, state_file, now=lambda: moment)
    answered = answer_question(
        engine,
        Ask(question=question, lang=Lang.EN, sources=SourceAdmission.APPROVED_ONLY),
    )
    return answered.response.packages[0].kind.value


def test_the_corpus_has_entries() -> None:
    """A guard on the loader: a glob that silently matched nothing would make every
    assertion below vacuous, and the suite would go green by finding no work."""
    assert len(CORPUS) > 90


@pytest.mark.parametrize(
    ("identifier", "question", "expected", "when"),
    [pytest.param(*row, id=row[0] or row[1][:40]) for row in CORPUS],
)
def test_the_corpus_entry_reaches_its_expected_outcome(
    databases: Databases,
    state_file: Path,
    identifier: str,
    question: str,
    expected: str,
    when: str,
) -> None:
    outcome = _outcome(databases, state_file, question, when)
    if identifier in KNOWN_GAPS:
        pytest.skip(f"known gap -- {KNOWN_GAPS[identifier]}")
    assert outcome == expected, (
        f"{identifier}: asked {question!r} expecting a {expected}, got a {outcome}. "
        "If this is a deliberate change, the corpus entry is what states the intent -- "
        "change it there, with a `why`, rather than here."
    )


def test_the_known_gaps_are_exactly_the_failures(
    databases: Databases, state_file: Path
) -> None:
    """The gap list is exact in both directions, and the second one is the point.

    An entry that has started passing must be **removed** from ``KNOWN_GAPS``, and this
    test fails until it is. Without that, a list written once decays into a list of
    things nobody has checked since, and a fix lands without anyone noticing it landed.
    """
    fixed: list[str] = []
    newly_broken: list[str] = []
    for identifier, question, expected, when in CORPUS:
        outcome = _outcome(databases, state_file, question, when)
        if identifier in KNOWN_GAPS and outcome == expected:
            fixed.append(f"{identifier} ({KNOWN_GAPS[identifier]})")
        if identifier not in KNOWN_GAPS and outcome != expected:
            newly_broken.append(f"{identifier}: expected {expected}, got {outcome}")

    assert not fixed, (
        "these entries now reach their expected outcome -- delete them from KNOWN_GAPS:\n  "
        + "\n  ".join(fixed)
    )
    assert not newly_broken, (
        "these entries regressed and are not listed as known gaps:\n  "
        + "\n  ".join(newly_broken)
    )
